# Use an official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy just the requirements.txt initially to leverage Docker cache
COPY ./Backend/python_orm/requirements.txt ./

# Install any needed packages specified in requirements.txt
# and make sure pip is up-to-date
RUN pip install --upgrade pip \
    && pip install wheel \
    && pip install -r requirements.txt

# Copy the rest of the application
COPY ./Backend/python_orm .

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]
