FROM node:20

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY ./polyclinic/package*.json ./

# Install dependencies.
RUN npm install


# Copy the rest of your application code
COPY ./polyclinic .

# The port your app will run on
EXPOSE 5173

CMD ["npm", "run", "dev"]

